#!/usr/bin/env bash
source "$(print_debarchiver_config.pl)"
set -e
set -x
#cd "$DESTDIR/.."
apt-ftparchive -o APT::FTPArchive::AlwaysStat=true -c "$1/.apt-ftparchive1.conf" release "$1" > "$1"/Release
rm "$1"/Release.gpg
gpg -a -b -s -u andrew.tapia@uky.edu -o "$1"/Release.gpg "$1"/Release
