name: markdown-autodocs

on:
  push:
    branches:
      - '*'

jobs:
  auto-update-readme:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          output_file_paths: '[./README.md]'
          commit_message: Update config file in README.
